'use client'

import { useState } from 'react'
import { ArrowRight, Check, ChevronDown, CircleCheck, FileText, Flame, Menu, Minus, Radio, ShieldCheck, Thermometer, WifiOff, X, Zap } from 'lucide-react'

const faqs = [
  ['Will my inspector actually accept digital logs?', 'Many health departments do, as long as you can pull them up on the spot — which is exactly what Inspector Mode is for. Some still prefer paper, so every report exports to a clean PDF you can print. Requirements vary by county; always verify with your local health authority.'],
  ['What if I have no signal at my spot?', "That's the normal case, not the edge case. Solo Truck saves every log on your phone instantly and syncs when you're back in coverage. You'll see exactly what's waiting to sync — nothing disappears."],
  ['Do I need to buy sensors or special thermometers?', 'No. Use the probe thermometer you already own. You read it, you tap it in, done. No hardware to buy, pair, or replace.'],
  ['Can I fix a log if I typed the wrong number?', "Yes — you add a correction with a note, and both entries stay visible. Records can't be silently edited or deleted, because that's precisely what makes them credible when an inspector is looking at them."],
  ['Is this a HACCP plan?', "No — and that's on purpose. If you need a HACCP plan or binder, tools exist for that (and they're good). Solo Truck is what happens after setup: the daily logging that keeps your operation inspection-ready, every single shift."],
  ['What happens to my records if I cancel?', "You keep read access and can export everything to PDF or CSV, forever. We don't hold your compliance history hostage — it's yours."],
]

const features = [
  ['Works with zero bars', 'Log inside your steel box with no signal. Everything queues on your phone and syncs the moment you\'re back online — nothing is ever lost.', WifiOff],
  ['Timestamps you can\'t fake', 'Every entry is stamped the second you save it and can\'t be edited after the fact. That\'s not a limitation — that\'s what makes your records worth trusting.', Radio],
  ['Corrective actions, guided', 'Out-of-range readings walk you through the fix and attach it to the log — the exact paper trail inspectors respect most.', ShieldCheck],
  ['Permit & document vault', 'Permits, commissary agreement, food manager cert — photographed once, always on hand, with a heads-up 30 days before anything expires.', FileText],
  ['Reminders that respect your day', 'Nudges during your service hours only. Day off? Total silence. Your streak counter turns compliance into a habit you\'ll actually keep.', Zap],
  ['Your data, always yours', 'Export everything to PDF or CSV any time. Even if you cancel, you can still read and export your records. No hostages here.', Check],
] as const

export default function Page() {
  const [openFaq, setOpenFaq] = useState<number | null>(0)
  return (
    <main className="landing-page">
      <header className="site-nav"><a href="#top" className="brand"><span className="brand-mark"><Flame size={19} fill="currentColor" /></span>Solo Truck</a><nav className="desktop-nav"><a href="#how">How it works</a><a href="#features">Features</a><a href="#pricing">Pricing</a><a href="#faq">FAQ</a></nav><a className="button button-dark nav-cta" href="#pricing">Start free trial <ArrowRight size={16} /></a><button className="mobile-menu" aria-label="Open menu"><Menu size={22} /></button></header>

      <section className="hero" id="top"><div className="hero-copy"><p className="eyebrow"><span className="eyebrow-dot" />For independent food trucks · US</p><h1>The inspector<br />doesn&apos;t call ahead.<br /><em>Be ready anyway.</em></h1><p className="hero-sub">Solo Truck replaces the greasy clipboard on your fridge. Log temps in 30 seconds, catch problems before they cost you product, and hand any inspector 90 days of honest, time-stamped records — in one tap.</p><div className="hero-actions"><a className="button button-flame" href="#pricing">Start your free trial <ArrowRight size={17} /></a><a className="button button-outline" href="#how">See how it works <span className="play">▶</span></a></div><p className="microcopy"><Check size={14} />14-day free trial · No credit card · Works offline</p></div><div className="hero-visual"><div className="inspection-stamp"><CircleCheck size={16} /> A — INSPECTION<br /><strong>PASSED</strong></div><div className="phone"><div className="phone-top"><span>9:41</span><span>▮▮▮ ◉</span></div><div className="phone-screen"><div className="screen-head"><div><span className="screen-label">WED, SEP 18</span><strong>Today</strong></div><span className="sync"><span /> SYNCED</span></div><div className="streak"><Flame size={18} fill="currentColor" /> <strong>23-day streak</strong><span>↗</span></div><div className="temp-list"><TempRow name="Walk-in fridge" time="Logged 10:42 AM" temp="37.4°F" /><TempRow name="Hot hold — chili" time="Logged 10:44 AM" temp="141°F" /><TempRow name="Prep fridge" time="Logged 10:45 AM" temp="44.1°F" flagged /></div><button className="temp-button"><Thermometer size={20} />Log a temp <ArrowRight size={17} /></button></div></div></div></section>

      <div className="ticker"><div className="ticker-track">06:58 AM — Pre-shift checklist complete (12/12) <span>◆</span> 07:15 AM — Walk-in fridge 38.1°F <span>◆</span> 11:02 AM — Prep fridge 44.1°F → moved food, adjusted dial <b>(flagged)</b> <span>◆</span> 11:26 AM — Prep fridge 39.8°F — back in range <span>◆</span> 02:30 PM — Hot hold 139°F <span>◆</span> 04:47 PM — Inspector Mode opened · 90-day report exported <span>◆</span></div></div>

      <section className="section paper-section" id="how"><div className="section-intro"><p className="eyebrow">Sound familiar?</p><h2>Paper logs are where<br /><em>good trucks go to fail.</em></h2></div><div className="story-grid"><StoryCard stamp="Every routine inspection" title="Paperwork first, fridge second" text="Before an inspector opens a single cooler, they ask for your logs — and most expect 30–90 days of history. A soggy, half-filled clipboard is the fastest way to turn a routine visit into a deep dig." /><StoryCard stamp="Inspectors know this trick" title="&quot;Perfect&quot; logs get you flagged" text="A column of 38°F written in the same pen, five minutes before the inspector walked up? They've seen it a thousand times. Fake-perfect paper logs invite scrutiny. Honest ones with corrective actions pass." /><StoryCard stamp="One bad day" title="Failing costs more than a fine" text="A cooler that quietly died overnight can mean $500 of product in the trash, a failing grade, and your truck's name in the local paper. The trucks that survive catch it at 44°F — not 49°F." /></div></section>

      <section className="truth-panel"><div className="truth-copy"><p className="eyebrow mint">The part nobody tells you</p><h2>Honest logs pass.<br /><em>We make honest<br />the easy way.</em></h2><p>Solo Truck doesn&apos;t help you look perfect — it helps you prove you&apos;re paying attention. Every entry gets a real timestamp the moment you tap save, even with zero signal inside your steel box. Caught a temp out of range? The app walks you through the corrective action and attaches it to the record. That&apos;s exactly the story inspectors want to see.</p></div><blockquote><span>“</span>If it isn&apos;t documented, you didn&apos;t do it.<footer>Temperature logs are the first records most health inspectors review — and a log that shows a problem plus the fix reads better than a log that&apos;s suspiciously spotless.</footer></blockquote></section>

      <section className="section steps-section"><div className="section-intro"><p className="eyebrow">Built for a hot kitchen and one free hand</p><h2>Three habits.<br /><em>Thirty seconds each.</em></h2></div><div className="steps-grid"><Step n="01" meta="~2 min · before you open" title="Run the pre-shift check" text="Tap through the 12 things inspectors actually look for — hand sink stocked, sanitizer at strength, raw below ready-to-eat, tanks tight. Open the window knowing you'd pass right now." /><Step n="02" meta="~30 sec · a few times a day" title="Log temps as you cook" text="Tap the fridge, punch the number, done. Out of range? The app asks what you did about it — moved food, adjusted the dial, tossed it — and saves the fix with the reading. No signal needed; it syncs later." /><Step n="03" meta="1 tap · when it counts" title="Hand over Inspector Mode" text="Inspector at the window? One tap opens a clean, read-only report: 90 days of logs, checklists, permits, and corrective actions. Export a PDF on the spot if they want paper." /></div></section>

      <section className="section feature-section" id="features"><div className="section-intro centered"><p className="eyebrow">Everything you need. Nothing you don&apos;t.</p><h2>Built for one truck,<br /><em>not a restaurant chain.</em></h2><p>No sensors to buy. No staff training day. No 40-page setup. If you can text, you can run Solo Truck.</p></div><div className="feature-grid">{features.map(([title, text, Icon]) => <article className="feature-card" key={title}><Icon size={22} /><h3>{title}</h3><p>{text}</p></article>)}</div></section>

      <section className="section compare-section"><div className="section-intro"><p className="eyebrow">Where Solo Truck fits</p><h2>The missing <em>middle.</em></h2><p>Binder generators set you up, then leave you with paper. Enterprise platforms start at $169/month and assume you have a staff. You need the layer in between.</p></div><div className="comparison"><div className="compare-row compare-head"><span>What you need</span><span>Binder generators</span><span>Solo Truck</span><span>Enterprise platforms</span></div>{[['Daily digital temp logs','Paper sheets to print','Yes — 30 sec/entry','Yes'],['Works offline in the truck','—','Yes, built for it','Varies'],['One-tap inspector report','—','Yes + PDF on the spot','Yes'],['Setup time','Minutes','5 minutes','Days + training'],['Built for a 1–3 person truck','Partly','Entirely','No — chains & kitchens'],['Price','~$50–100 once','$24/month','$169+/month']].map(row => <div className="compare-row" key={row[0]}>{row.map((cell, i) => <span className={i === 2 ? 'solo-cell' : ''} key={cell}>{cell}</span>)}</div>)}</div><p className="caption">Already have a HACCP binder? Great — keep it. Solo Truck is what keeps it alive between inspections.</p></section>

      <section className="section pricing-section" id="pricing"><div className="section-intro centered"><p className="eyebrow">Pricing</p><h2>Less than one failed<br /><em>batch of chili.</em></h2></div><div className="plans"><Plan title="Monthly" price="$24/month" detail="Unlimited logs & checklists" /><Plan featured title="Yearly" price="$190/year" detail="Save 34% vs. monthly" /></div><div className="included">{['Unlimited temp logs & checklists','Inspector Mode + PDF export','Document vault with expiry alerts','Offline logging & sync','Email support from a real human'].map(item => <span key={item}><Check size={15} />{item}</span>)}</div><p className="pricing-note">14-day free trial · No credit card required · <a href="/pricing">Full pricing details</a></p></section>

      <section className="cta-section"><p className="eyebrow">Ready when you are</p><h2>Start logging in<br /><em>5 minutes.</em></h2><p>14 days free, no credit card. Set up your truck, log your first temp, and see for yourself whether it fits your shift.</p><div className="hero-actions"><a className="button button-light" href="#pricing">Start your free trial <ArrowRight size={17} /></a><a className="button button-ghost" href="mailto:hello@solotruck.com">Or apply for Founding Trucks — 3 months free</a></div><small>Founding Trucks: first 20 trucks get 3 months free + a direct line to the founder, in exchange for 15 minutes of feedback a week.</small></section>

      <section className="section faq-section" id="faq"><div className="section-intro"><p className="eyebrow">Questions</p><h2>Fair questions,<br /><em>straight answers.</em></h2></div><div className="faq-list">{faqs.map(([question, answer], i) => <div className={`faq-item ${openFaq === i ? 'open' : ''}`} key={question}><button onClick={() => setOpenFaq(openFaq === i ? null : i)}><span>{String(i + 1).padStart(2, '0')}</span>{question}<ChevronDown size={19} /></button>{openFaq === i && <p>{answer}</p>}</div>)}</div></section>

      <footer className="footer"><div><a className="brand" href="#top"><span className="brand-mark"><Flame size={19} fill="currentColor" /></span>Solo Truck</a><p>Inspector-proof daily logs for independent food trucks.</p></div><div className="footer-links"><a href="#how">How it works</a><a href="#pricing">Pricing</a><a href="#faq">FAQ</a><a href="#pricing">Start free trial</a><a href="mailto:hello@solotruck.com">Founding Trucks</a><a href="#features">Guide</a></div><p className="legal">Solo Truck is a record-keeping tool, not legal or food-safety advice, and does not guarantee inspection outcomes. Default thresholds follow the FDA Food Code; actual requirements vary by state and county — always verify with your local health authority. © 2026 Solo Truck.</p></footer>
    </main>
  )
}

function TempRow({ name, time, temp, flagged = false }: { name: string; time: string; temp: string; flagged?: boolean }) { return <div className={`temp-row ${flagged ? 'flagged' : ''}`}><span className="status-dot" /><div><strong>{name}</strong><small>{time}</small></div><div className="temp-reading"><b>{temp}</b><small>{flagged ? 'Action' : 'In range'}</small></div></div> }
function StoryCard({ stamp, title, text }: { stamp: string; title: string; text: string }) { return <article className="story-card"><span className="card-stamp">{stamp}</span><h3>{title}</h3><p>{text}</p><Minus size={21} /></article> }
function Step({ n, meta, title, text }: { n: string; meta: string; title: string; text: string }) { return <article className="step"><span className="step-number">{n}</span><p className="step-meta">{meta}</p><h3>{title}</h3><p>{text}</p></article> }
function Plan({ title, price, detail, featured = false }: { title: string; price: string; detail: string; featured?: boolean }) { return <article className={`plan ${featured ? 'featured' : ''}`}>{featured && <span className="popular">BEST VALUE</span>}<p className="plan-title">{title}</p><h3>{price}</h3><p>{detail}</p><a className={`button ${featured ? 'button-flame' : 'button-outline'}`} href="#top">Start free trial <ArrowRight size={16} /></a></article> }

